name: GitHub Actions Practice

on:
  push:

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls
